//This tool is used to add renderings of files in a chat message.

import { tool } from "@langchain/core/tools";
import { z } from "zod";

const renderAssetToolSchema = z.object({
    filePath: z.string().describe("Path to the asset file to be rendered"),
    title: z.string().optional().describe("Optional title to display above the rendered asset"),
    description: z.string().optional().describe("Optional description of what the asset represents")
});

export const renderAssetTool = tool(
    async (renderAssetToolArgs) => {
        return {
            ...renderAssetToolArgs,
            renderType: 'asset' // Indicates to frontend this is an asset to be rendered
        };
    },
    {
        name: "renderAssetTool",
        description: `
Tool for rendering various types of assets (HTML files, plots, images) in the chat interface.
Use this when you want to display visual content generated by the AI.
The frontend will handle the actual rendering based on the file path and asset type provided.

Examples:
- Displaying HTML files with interactive plots
- Showing generated charts or diagrams
- Rendering data visualizations
`,
        schema: renderAssetToolSchema,
    }
);